#
# This is a GemInstaller config file (http://geminstaller.rubyforge.org)
#
# This is a list of all gems needed to work with watircuke
#
# MAC OSX INSTLLATION


defaults:
  install_options: --include-dependencies
gems: 
- name: gherkin
- name: cucumber
- name: firewatir
- name: rb-appscript
- name: safariwatir
- name: syntax
- name: colorize
- name: chronic                                                       
- name: ruby-debug
- name: watir-webdriver
- name: rspec
- name: nokogiri
- name: sys-proctable --platform="x86-darwin-8"
- name: fileutils
- name: httparty
- name: mime-types
- name: sqlite3-ruby
- name: rails -v 2.3.8
- name: nokogiri
- name: diff-lcs