--- 
#
# This is a GemInstaller config file (http://geminstaller.rubyforge.org)
#
# This is a list of all gems needed to work with watircuke
#
defaults:
  install_options: --include-dependencies
gems: 
- name: gherkin
- name: cucumber
- name: watir
- name: firewatir
- name: rb-appscript
- name: safariwatir
- name: syntax
- name: colorize
- name: chronic                                                       
- name: win32console
- name: ruby-debug
- name: watir-webdriver
- name: rspec
- name: nokogiri
- name: win32-open3
- name: sys-proctable  #gem install sys-proctable --platform=...
- name: fileutils
- name: httparty
- name: mime-types